name: E2E Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      - name: Install dependencies
        run: npm install

      - name: Run E2E Tests
        run: npm run test:e2e

      - name: Generate E2E Report
        run: npm run report:e2e

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: E2E Test Report
          path: cypress/reports/*.html  
